// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDixNV5r9TDIGgfo9Tplt32bMpVDl3Boq0',
    appId: '1:752289234163:web:092f1ba725b42732e7cb86',
    messagingSenderId: '752289234163',
    projectId: 'ecommerce-app-bf73d',
    authDomain: 'ecommerce-app-bf73d.firebaseapp.com',
    storageBucket: 'ecommerce-app-bf73d.firebasestorage.app',
    measurementId: 'G-YKCNN48610',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX5GqF82ruCn6r4hCoUYVOGnNjatFbssg',
    appId: '1:752289234163:android:7b43e8738ac3c603e7cb86',
    messagingSenderId: '752289234163',
    projectId: 'ecommerce-app-bf73d',
    storageBucket: 'ecommerce-app-bf73d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzYN0QNfSbXI4z8HJM5Df2DWj1QFxibo',
    appId: '1:752289234163:ios:c36965dc1ae6f39fe7cb86',
    messagingSenderId: '752289234163',
    projectId: 'ecommerce-app-bf73d',
    storageBucket: 'ecommerce-app-bf73d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzYN0QNfSbXI4z8HJM5Df2DWj1QFxibo',
    appId: '1:752289234163:ios:c36965dc1ae6f39fe7cb86',
    messagingSenderId: '752289234163',
    projectId: 'ecommerce-app-bf73d',
    storageBucket: 'ecommerce-app-bf73d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDixNV5r9TDIGgfo9Tplt32bMpVDl3Boq0',
    appId: '1:752289234163:web:92522d56fc72466de7cb86',
    messagingSenderId: '752289234163',
    projectId: 'ecommerce-app-bf73d',
    authDomain: 'ecommerce-app-bf73d.firebaseapp.com',
    storageBucket: 'ecommerce-app-bf73d.firebasestorage.app',
    measurementId: 'G-7V9J034EXM',
  );
}
